### ISSUE TITLE
GET /status "call" never return status "ended"

### ISSUE THREAD

**Issue by joseandrespr** [CounterPathAPI/DesktopAPI_1.2_Sample#6]
Hi,
We are in the process of writing an integration with the javascript websocket api.  We have almost everything working except we are unable to detect when a call has ended.  According to the documentation the "ended" status is part of the Outgoing/Incoming call states, I have attached a screenshot of the documentation I refer to: 

![BriaAPIRefGetCalls](https://user-images.githubusercontent.com/6821354/86018857-e21d8b80-b9f3-11ea-9eec-f258734a9a86.PNG)

I have tried with the included javascript example project and I do not see it there either, am I missing something?  Thanks in advance for any help you can provide to assist us with this matter.

**Comment by jpchow26** [comment]
Hi Joseph,

What version of Bria are you using?

**Comment by joseandrespr** [comment]
Hi, Bria Version is 6.1.0 Build 103104

**Comment by jpchow26** [comment]
Hi Joseph,

Our documentation is mis-leading and needs an update around the ended state.

When call in Bria enters the "ended" state, it will POST a statusChange of type "call" to your API client that the call has ended. When you then GET a "status" of type "call", it's up to your API client to parse the returned call list between subsequent "call" status queries. When you see that a previous call has been removed from the call list then you know it has been ended.

This is a bit awkward because we don't actually POST call statuses. We only return calls on request, and a call in an ended state is only there for a fraction of a second so you will never see the "ended" call state.
